Introdução ao framework Pytorch! 

In [7]:
## Importação da biblioteca
import torch

## oque Tensores são?
## É o equivalente matemático a uma matriz

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.tensor(lista)

print(lista)
print('-----------------------------------------------------------')
print(tensor)

[[1, 2, 3], [4, 5, 6]]
-----------------------------------------------------------
tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
## Padrões de tipos dos tensores mais utilizados

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
tensor = torch.LongTensor(lista)
print(tensor.dtype)
tensor = torch.FloatTensor(lista)
print(tensor.dtype)

torch.float64
torch.int64
torch.float32


In [17]:
## gerando tensores

## tensor cheio de 0
tensor0 = torch.zeros(2,2)

## tensor cheio de 1
tensor1 = torch.ones(2,2)

## tensor aleatório
randonTensor = torch.rand(2,2)

print(tensor0)
print('-------------------------------')
print(tensor1)
print('-------------------------------')
print(randonTensor)
print('-------------------------------')

tensor([[0., 0.],
        [0., 0.]])
-------------------------------
tensor([[1., 1.],
        [1., 1.]])
-------------------------------
tensor([[0.0327, 0.5574],
        [0.4200, 0.0269]])
-------------------------------


In [22]:
## É possivel criar tensores a partir de arrays Numpy
import numpy as np

## gerando array aleatório Numpy
array = np.random.rand(5,5)

## convertendo array Numpy para tensor
tensor = torch.from_numpy(array)

print(type(array))
print(type(tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [21]:
## Assim como é possivel converter tensores para arrays Numpy

tensor = torch.ones(2,2)

array = tensor.data.numpy()

print(type(tensor))
print(type(array))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [27]:
## Acessando e modificando itens de um tensor

tensor = torch.ones(3,3)

print('antes da alteração')
print(tensor)
print('')

## alterando 1 elemento
tensor[1,1] = 0

print('1 elemento alterado')
print(tensor)
print('')

## alterando 1 linha
tensor[0:1] = 0

print('1 linha alterada')
print(tensor)
print('')

## alterando 1 coluna
tensor[:,1] = 2

print('1 coluna alterada')
print(tensor)



antes da alteração
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

1 elemento alterado
tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])

1 linha alterada
tensor([[0., 0., 0.],
        [1., 0., 1.],
        [1., 1., 1.]])

1 coluna alterada
tensor([[0., 2., 0.],
        [1., 2., 1.],
        [1., 2., 1.]])


In [34]:
## Equações entre tensores

tensorA = torch.ones(2,2)
tensorB = torch.tensor([[0,1],
                        [2,3]])
print('A')
print(tensorA)
print('')
print('B')
print(tensorB)
print('')


## As equações são feitas com os elementos que tem sua respectiva posição em outro tensor 
## por isso é importante ressaltar que os tensores devem ter a mesma dimensão
print('A x B')
print(tensorA*tensorB)

A
tensor([[1., 1.],
        [1., 1.]])

B
tensor([[0, 1],
        [2, 3]])

A x B
tensor([[0., 1.],
        [2., 3.]])


In [39]:
## Dimensões

tensor = torch.ones(2,2,3)

print('Tensor')
print(tensor)
print('')
print('Dimensão')

## Consultando a dimensão do tensor
print(tensor.size())
print('')
print('')

## Redimensionando o tensor
tensor = tensor.view(4,3)

print('Tensor redimensionado')
print(tensor)
print('')
print('Dimensão nova')
print(tensor.size())
print('')
print('')

## Redimensionando achatado
tensor = tensor.view(-1)

print('Tensor achatado (colocado em uma unica linha)')
print(tensor)
print('')
print('Dimensão nova')
print(tensor.size())
print('')
print('')




Tensor
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

Dimensão
torch.Size([2, 2, 3])


Tensor redimensionado
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Dimensão nova
torch.Size([4, 3])


Tensor achatado (colocado em uma unica linha)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Dimensão nova
torch.Size([12])




In [3]:
## definindo o hardware que vai ser utilizado
import torch

tensor = torch.ones(5,5)

##verifica se a GPU está disponível para uso 
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

##coloca o tensor na GPU
tensor = tensor.to(device)

print(tensor)
print('')
print(device)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

cuda
